cloud:
  aws:
    credentials:
      access-key: {보안을 위해 업로드 추가 수정}
      secret-key: {보안을 위해 업로드 추가 수정}
    s3:
      bucket: saypart/ #버킷 이름
    region:
      static: ap-northeast-2 # 리전 정보
    stack:

      auto: false

logging.config: classpath:logback/logback-server.xml

